// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7vKXJ6EAs24qnU9RSWqEKT
// Component: 3dK3yPpS5Fc6D6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import Button from "../../Button"; // plasmic-import: 1dNB0d53gYBxGU/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_copy_of_new_template.module.css"; // plasmic-import: 7vKXJ6EAs24qnU9RSWqEKT/projectcss
import sty from "./PlasmicAccountPage.module.css"; // plasmic-import: 3dK3yPpS5Fc6D6/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: ZnDh5JA_TnR6DC/icon
import Frame6Icon from "./icons/PlasmicIcon__Frame6"; // plasmic-import: D67GLiwwFzZ5mz/icon
import Frame7Icon from "./icons/PlasmicIcon__Frame7"; // plasmic-import: gwjcSz4Xyf1n-h/icon
import Frame8Icon from "./icons/PlasmicIcon__Frame8"; // plasmic-import: Pqgrb6Gq8dQU2d/icon
import Frame9Icon from "./icons/PlasmicIcon__Frame9"; // plasmic-import: uE7K7GhNhsPkMq/icon
import Frame10Icon from "./icons/PlasmicIcon__Frame10"; // plasmic-import: V0vazdoZOhhhBG/icon

export const PlasmicAccountPage__VariantProps = new Array();

export const PlasmicAccountPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicAccountPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <GraphqlFetcher
            data-plasmic-name={"graphQlFetcher"}
            data-plasmic-override={overrides.graphQlFetcher}
            className={classNames("__wab_instance", sty.graphQlFetcher)}
            dataName={"fetchedData"}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"POST"}
            noLayout={false}
            query={{
              query:
                "query MyQuery($name: String) {\n  characters(filter: {name: $name}) {\n    results {\n      name\n      species\n      image\n    }\n  }\n}\n",
              variables: { name: "Rick Sanchez" }
            }}
            url={"https://rickandmortyapi.com/graphql"}
            varOverrides={{}}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <div
                    data-plasmic-name={"accountDetails"}
                    data-plasmic-override={overrides.accountDetails}
                    className={classNames(projectcss.all, sty.accountDetails)}
                  >
                    <div
                      data-plasmic-name={"frame"}
                      data-plasmic-override={overrides.frame}
                      className={classNames(projectcss.all, sty.frame)}
                    >
                      <div
                        data-plasmic-name={"frame2"}
                        data-plasmic-override={overrides.frame2}
                        className={classNames(projectcss.all, sty.frame2)}
                      >
                        <div
                          data-plasmic-name={"image"}
                          data-plasmic-override={overrides.image}
                          className={classNames(projectcss.all, sty.image)}
                        />

                        <div
                          data-plasmic-name={"accountDetails2"}
                          data-plasmic-override={overrides.accountDetails2}
                          className={classNames(
                            projectcss.all,
                            sty.accountDetails2
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__k6ZMo
                            )}
                          >
                            {"Account Details"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"accountDetails3"}
                          data-plasmic-override={overrides.accountDetails3}
                          className={classNames(
                            projectcss.all,
                            sty.accountDetails3
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__t9Lkl
                            )}
                          >
                            {"Account Details"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"accountDetails4"}
                          data-plasmic-override={overrides.accountDetails4}
                          className={classNames(
                            projectcss.all,
                            sty.accountDetails4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yqRjq
                            )}
                          >
                            {"Account Details"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"defaultAddress"}
                        data-plasmic-override={overrides.defaultAddress}
                        className={classNames(
                          projectcss.all,
                          sty.defaultAddress
                        )}
                      >
                        <div
                          data-plasmic-name={"defaultAddress2"}
                          data-plasmic-override={overrides.defaultAddress2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.defaultAddress2
                          )}
                        >
                          {"Default Address : "}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame4"}
                        data-plasmic-override={overrides.frame4}
                        className={classNames(projectcss.all, sty.frame4)}
                      >
                        <div
                          data-plasmic-name={"_125JkNagar"}
                          data-plasmic-override={overrides._125JkNagar}
                          className={classNames(
                            projectcss.all,
                            sty._125JkNagar
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gjIwr
                            )}
                          >
                            {"125, JK Nagar"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame5"}
                        data-plasmic-override={overrides.frame5}
                        className={classNames(projectcss.all, sty.frame5)}
                      >
                        <div
                          data-plasmic-name={"noida"}
                          data-plasmic-override={overrides.noida}
                          className={classNames(projectcss.all, sty.noida)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gzHHk
                            )}
                          >
                            {"Noida"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame6"}
                        data-plasmic-override={overrides.frame6}
                        className={classNames(projectcss.all, sty.frame6)}
                      >
                        <div
                          data-plasmic-name={"frame7"}
                          data-plasmic-override={overrides.frame7}
                          className={classNames(projectcss.all, sty.frame7)}
                        >
                          <div
                            data-plasmic-name={"group"}
                            data-plasmic-override={overrides.group}
                            className={classNames(projectcss.all, sty.group)}
                          >
                            <div
                              data-plasmic-name={"group2"}
                              data-plasmic-override={overrides.group2}
                              className={classNames(projectcss.all, sty.group2)}
                            >
                              <div
                                data-plasmic-name={"group3"}
                                data-plasmic-override={overrides.group3}
                                className={classNames(
                                  projectcss.all,
                                  sty.group3
                                )}
                              >
                                <div
                                  data-plasmic-name={"group4"}
                                  data-plasmic-override={overrides.group4}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group4
                                  )}
                                >
                                  <GroupIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__mTjjj
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"_211378"}
                          data-plasmic-override={overrides._211378}
                          className={classNames(projectcss.all, sty._211378)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__efcNl
                            )}
                          >
                            {"211378"}
                          </div>
                        </div>
                      </div>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__fJmFu
                        )}
                        link={`/update-address`}
                      >
                        {"UPDATE ADDRESS"}
                      </Button>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__mHkaw
                        )}
                        link={`/add-new-address`}
                      >
                        {"ADD NEW ADDRESS"}
                      </Button>
                    </div>
                    <div
                      data-plasmic-name={"frame8"}
                      data-plasmic-override={overrides.frame8}
                      className={classNames(projectcss.all, sty.frame8)}
                    >
                      <div
                        data-plasmic-name={"frame9"}
                        data-plasmic-override={overrides.frame9}
                        className={classNames(projectcss.all, sty.frame9)}
                      />

                      <div
                        data-plasmic-name={"frame10"}
                        data-plasmic-override={overrides.frame10}
                        className={classNames(projectcss.all, sty.frame10)}
                      >
                        <div
                          data-plasmic-name={"emailAddress"}
                          data-plasmic-override={overrides.emailAddress}
                          className={classNames(
                            projectcss.all,
                            sty.emailAddress
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ohDeh
                            )}
                          >
                            {"Email address"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame11"}
                        data-plasmic-override={overrides.frame11}
                        className={classNames(projectcss.all, sty.frame11)}
                      >
                        <div
                          data-plasmic-name={"joye"}
                          data-plasmic-override={overrides.joye}
                          className={classNames(projectcss.all, sty.joye)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__p5QXn
                            )}
                          >
                            {"Joye"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame12"}
                        data-plasmic-override={overrides.frame12}
                        className={classNames(projectcss.all, sty.frame12)}
                      >
                        <div
                          data-plasmic-name={"sharma"}
                          data-plasmic-override={overrides.sharma}
                          className={classNames(projectcss.all, sty.sharma)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pxs3
                            )}
                          >
                            {"Sharma"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame13"}
                        data-plasmic-override={overrides.frame13}
                        className={classNames(projectcss.all, sty.frame13)}
                      >
                        <div
                          data-plasmic-name={"_78Xxxxxxxxx"}
                          data-plasmic-override={overrides._78Xxxxxxxxx}
                          className={classNames(
                            projectcss.all,
                            sty._78Xxxxxxxxx
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rmxXo
                            )}
                          >
                            {"78XXXXXXXXX"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame14"}
                        data-plasmic-override={overrides.frame14}
                        className={classNames(projectcss.all, sty.frame14)}
                      >
                        <div
                          data-plasmic-name={"frame15"}
                          data-plasmic-override={overrides.frame15}
                          className={classNames(projectcss.all, sty.frame15)}
                        >
                          <div
                            data-plasmic-name={"group5"}
                            data-plasmic-override={overrides.group5}
                            className={classNames(projectcss.all, sty.group5)}
                          >
                            <div
                              data-plasmic-name={"group6"}
                              data-plasmic-override={overrides.group6}
                              className={classNames(projectcss.all, sty.group6)}
                            >
                              <div
                                data-plasmic-name={"group7"}
                                data-plasmic-override={overrides.group7}
                                className={classNames(
                                  projectcss.all,
                                  sty.group7
                                )}
                              >
                                <div
                                  data-plasmic-name={"group8"}
                                  data-plasmic-override={overrides.group8}
                                  className={classNames(
                                    projectcss.all,
                                    sty.group8
                                  )}
                                >
                                  <GroupIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__n1Uu
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"india"}
                          data-plasmic-override={overrides.india}
                          className={classNames(projectcss.all, sty.india)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__f3S7I
                            )}
                          >
                            {"India"}
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame16"}
                        data-plasmic-override={overrides.frame16}
                        className={classNames(projectcss.all, sty.frame16)}
                      />

                      <div
                        data-plasmic-name={"frame17"}
                        data-plasmic-override={overrides.frame17}
                        className={classNames(projectcss.all, sty.frame17)}
                      >
                        <div
                          data-plasmic-name={"rectangle"}
                          data-plasmic-override={overrides.rectangle}
                          className={classNames(projectcss.all, sty.rectangle)}
                        />

                        <div
                          data-plasmic-name={"male"}
                          data-plasmic-override={overrides.male}
                          className={classNames(projectcss.all, sty.male)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__q5XDn
                            )}
                          >
                            {"Male"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"frame18"}
                      data-plasmic-override={overrides.frame18}
                      className={classNames(projectcss.all, sty.frame18)}
                    >
                      <div
                        data-plasmic-name={"frame19"}
                        data-plasmic-override={overrides.frame19}
                        className={classNames(projectcss.all, sty.frame19)}
                      >
                        <div
                          data-plasmic-name={"frame20"}
                          data-plasmic-override={overrides.frame20}
                          className={classNames(projectcss.all, sty.frame20)}
                        >
                          <div
                            data-plasmic-name={"frame21"}
                            data-plasmic-override={overrides.frame21}
                            className={classNames(projectcss.all, sty.frame21)}
                          >
                            <div
                              data-plasmic-name={"frame22"}
                              data-plasmic-override={overrides.frame22}
                              className={classNames(
                                projectcss.all,
                                sty.frame22
                              )}
                            >
                              <div
                                data-plasmic-name={"findAStore"}
                                data-plasmic-override={overrides.findAStore}
                                className={classNames(
                                  projectcss.all,
                                  sty.findAStore
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__fsuU8
                                  )}
                                >
                                  {"Find A Store"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"becomeAMember"}
                                data-plasmic-override={overrides.becomeAMember}
                                className={classNames(
                                  projectcss.all,
                                  sty.becomeAMember
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__nWy4Y
                                  )}
                                >
                                  {"Become A Member"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"signUpForEmail"}
                                data-plasmic-override={overrides.signUpForEmail}
                                className={classNames(
                                  projectcss.all,
                                  sty.signUpForEmail
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__uLpv
                                  )}
                                >
                                  {"Sign Up for Email"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"sendUsFeedback"}
                                data-plasmic-override={overrides.sendUsFeedback}
                                className={classNames(
                                  projectcss.all,
                                  sty.sendUsFeedback
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__xLili
                                  )}
                                >
                                  {"Send Us Feedback"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"studentDiscounts"}
                                data-plasmic-override={
                                  overrides.studentDiscounts
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.studentDiscounts
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___0KCyz
                                  )}
                                >
                                  {"Student Discounts"}
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame23"}
                            data-plasmic-override={overrides.frame23}
                            className={classNames(projectcss.all, sty.frame23)}
                          >
                            <div
                              data-plasmic-name={"frame24"}
                              data-plasmic-override={overrides.frame24}
                              className={classNames(
                                projectcss.all,
                                sty.frame24
                              )}
                            >
                              <div
                                data-plasmic-name={"getHelp"}
                                data-plasmic-override={overrides.getHelp}
                                className={classNames(
                                  projectcss.all,
                                  sty.getHelp
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__kktNn
                                  )}
                                >
                                  {"Get Help"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"orderStatus"}
                                data-plasmic-override={overrides.orderStatus}
                                className={classNames(
                                  projectcss.all,
                                  sty.orderStatus
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___5Hq9H
                                  )}
                                >
                                  {"Order Status"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"delivery"}
                                data-plasmic-override={overrides.delivery}
                                className={classNames(
                                  projectcss.all,
                                  sty.delivery
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__g6R7L
                                  )}
                                >
                                  {"Delivery"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"returns"}
                                data-plasmic-override={overrides.returns}
                                className={classNames(
                                  projectcss.all,
                                  sty.returns
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__bOGf2
                                  )}
                                >
                                  {"Returns"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"paymentOptions"}
                                data-plasmic-override={overrides.paymentOptions}
                                className={classNames(
                                  projectcss.all,
                                  sty.paymentOptions
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__s23Rv
                                  )}
                                >
                                  {"Payment Options"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={
                                  "contactUsOnNikecomInquiries"
                                }
                                data-plasmic-override={
                                  overrides.contactUsOnNikecomInquiries
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.contactUsOnNikecomInquiries
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__j9Xfl
                                  )}
                                >
                                  {"Contact Us On Nike.com Inquiries"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={
                                  "contactUsOnAllOtherInquiries"
                                }
                                data-plasmic-override={
                                  overrides.contactUsOnAllOtherInquiries
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.contactUsOnAllOtherInquiries
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__hInM
                                  )}
                                >
                                  {"Contact Us On All Other Inquiries"}
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"frame25"}
                            data-plasmic-override={overrides.frame25}
                            className={classNames(projectcss.all, sty.frame25)}
                          >
                            <div
                              data-plasmic-name={"frame26"}
                              data-plasmic-override={overrides.frame26}
                              className={classNames(
                                projectcss.all,
                                sty.frame26
                              )}
                            >
                              <div
                                data-plasmic-name={"aboutNike"}
                                data-plasmic-override={overrides.aboutNike}
                                className={classNames(
                                  projectcss.all,
                                  sty.aboutNike
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__iajrU
                                  )}
                                >
                                  {"About Nike"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"news"}
                                data-plasmic-override={overrides.news}
                                className={classNames(projectcss.all, sty.news)}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__nPy2
                                  )}
                                >
                                  {"News"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"careers"}
                                data-plasmic-override={overrides.careers}
                                className={classNames(
                                  projectcss.all,
                                  sty.careers
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__j0XE
                                  )}
                                >
                                  {"Careers"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"investors"}
                                data-plasmic-override={overrides.investors}
                                className={classNames(
                                  projectcss.all,
                                  sty.investors
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__q6ZeV
                                  )}
                                >
                                  {"Investors"}
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"sustainability"}
                                data-plasmic-override={overrides.sustainability}
                                className={classNames(
                                  projectcss.all,
                                  sty.sustainability
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__eS5BH
                                  )}
                                >
                                  {"Sustainability"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame27"}
                          data-plasmic-override={overrides.frame27}
                          className={classNames(projectcss.all, sty.frame27)}
                        >
                          <div
                            data-plasmic-name={"frame28"}
                            data-plasmic-override={overrides.frame28}
                            className={classNames(projectcss.all, sty.frame28)}
                          >
                            <Frame6Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__uH2
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame29"}
                            data-plasmic-override={overrides.frame29}
                            className={classNames(projectcss.all, sty.frame29)}
                          >
                            <Frame7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__gWhXo
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame30"}
                            data-plasmic-override={overrides.frame30}
                            className={classNames(projectcss.all, sty.frame30)}
                          >
                            <Frame8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__umN9Z
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={"frame31"}
                            data-plasmic-override={overrides.frame31}
                            className={classNames(projectcss.all, sty.frame31)}
                          >
                            <Frame9Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___6JO
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"frame32"}
                        data-plasmic-override={overrides.frame32}
                        className={classNames(projectcss.all, sty.frame32)}
                      >
                        <div
                          data-plasmic-name={"frame33"}
                          data-plasmic-override={overrides.frame33}
                          className={classNames(projectcss.all, sty.frame33)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"autoLayoutHorizontal"}
                            data-plasmic-override={
                              overrides.autoLayoutHorizontal
                            }
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.autoLayoutHorizontal
                            )}
                          >
                            <div
                              data-plasmic-name={"frame34"}
                              data-plasmic-override={overrides.frame34}
                              className={classNames(
                                projectcss.all,
                                sty.frame34
                              )}
                            >
                              <Frame10Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___9Egvt
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7IHwk
                              )}
                            >
                              {"India"}
                            </div>
                          </p.Stack>
                          <div
                            data-plasmic-name={"_2023NikeIncAllRightsReserved"}
                            data-plasmic-override={
                              overrides._2023NikeIncAllRightsReserved
                            }
                            className={classNames(
                              projectcss.all,
                              sty._2023NikeIncAllRightsReserved
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ok8Vb
                              )}
                            >
                              {"© 2023 Nike, Inc. All Rights Reserved"}
                            </div>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"frame35"}
                          data-plasmic-override={overrides.frame35}
                          className={classNames(projectcss.all, sty.frame35)}
                        >
                          <div
                            data-plasmic-name={"guides"}
                            data-plasmic-override={overrides.guides}
                            className={classNames(projectcss.all, sty.guides)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vj0Uu
                              )}
                            >
                              {"Guides"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"termsOfSale"}
                            data-plasmic-override={overrides.termsOfSale}
                            className={classNames(
                              projectcss.all,
                              sty.termsOfSale
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__aMvNb
                              )}
                            >
                              {"Terms of Sale"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"termsOfUse"}
                            data-plasmic-override={overrides.termsOfUse}
                            className={classNames(
                              projectcss.all,
                              sty.termsOfUse
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__c8Rzw
                              )}
                            >
                              {"Terms of Use"}
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"nikePrivacyPolicy"}
                            data-plasmic-override={overrides.nikePrivacyPolicy}
                            className={classNames(
                              projectcss.all,
                              sty.nikePrivacyPolicy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ttQv1
                              )}
                            >
                              {"Nike Privacy Policy"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphqlFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "graphQlFetcher",
    "freeBox",
    "accountDetails",
    "frame",
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4",
    "defaultAddress",
    "defaultAddress2",
    "frame4",
    "_125JkNagar",
    "frame5",
    "noida",
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378",
    "frame8",
    "frame9",
    "frame10",
    "emailAddress",
    "frame11",
    "joye",
    "frame12",
    "sharma",
    "frame13",
    "_78Xxxxxxxxx",
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame16",
    "frame17",
    "rectangle",
    "male",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  graphQlFetcher: [
    "graphQlFetcher",
    "freeBox",
    "accountDetails",
    "frame",
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4",
    "defaultAddress",
    "defaultAddress2",
    "frame4",
    "_125JkNagar",
    "frame5",
    "noida",
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378",
    "frame8",
    "frame9",
    "frame10",
    "emailAddress",
    "frame11",
    "joye",
    "frame12",
    "sharma",
    "frame13",
    "_78Xxxxxxxxx",
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame16",
    "frame17",
    "rectangle",
    "male",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  freeBox: [
    "freeBox",
    "accountDetails",
    "frame",
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4",
    "defaultAddress",
    "defaultAddress2",
    "frame4",
    "_125JkNagar",
    "frame5",
    "noida",
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378",
    "frame8",
    "frame9",
    "frame10",
    "emailAddress",
    "frame11",
    "joye",
    "frame12",
    "sharma",
    "frame13",
    "_78Xxxxxxxxx",
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame16",
    "frame17",
    "rectangle",
    "male",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  accountDetails: [
    "accountDetails",
    "frame",
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4",
    "defaultAddress",
    "defaultAddress2",
    "frame4",
    "_125JkNagar",
    "frame5",
    "noida",
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378",
    "frame8",
    "frame9",
    "frame10",
    "emailAddress",
    "frame11",
    "joye",
    "frame12",
    "sharma",
    "frame13",
    "_78Xxxxxxxxx",
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame16",
    "frame17",
    "rectangle",
    "male",
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame: [
    "frame",
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4",
    "defaultAddress",
    "defaultAddress2",
    "frame4",
    "_125JkNagar",
    "frame5",
    "noida",
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378"
  ],

  frame2: [
    "frame2",
    "image",
    "accountDetails2",
    "accountDetails3",
    "accountDetails4"
  ],

  image: ["image"],
  accountDetails2: ["accountDetails2"],
  accountDetails3: ["accountDetails3"],
  accountDetails4: ["accountDetails4"],
  defaultAddress: ["defaultAddress", "defaultAddress2"],
  defaultAddress2: ["defaultAddress2"],
  frame4: ["frame4", "_125JkNagar"],
  _125JkNagar: ["_125JkNagar"],
  frame5: ["frame5", "noida"],
  noida: ["noida"],
  frame6: [
    "frame6",
    "frame7",
    "group",
    "group2",
    "group3",
    "group4",
    "_211378"
  ],

  frame7: ["frame7", "group", "group2", "group3", "group4"],
  group: ["group", "group2", "group3", "group4"],
  group2: ["group2", "group3", "group4"],
  group3: ["group3", "group4"],
  group4: ["group4"],
  _211378: ["_211378"],
  frame8: [
    "frame8",
    "frame9",
    "frame10",
    "emailAddress",
    "frame11",
    "joye",
    "frame12",
    "sharma",
    "frame13",
    "_78Xxxxxxxxx",
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india",
    "frame16",
    "frame17",
    "rectangle",
    "male"
  ],

  frame9: ["frame9"],
  frame10: ["frame10", "emailAddress"],
  emailAddress: ["emailAddress"],
  frame11: ["frame11", "joye"],
  joye: ["joye"],
  frame12: ["frame12", "sharma"],
  sharma: ["sharma"],
  frame13: ["frame13", "_78Xxxxxxxxx"],
  _78Xxxxxxxxx: ["_78Xxxxxxxxx"],
  frame14: [
    "frame14",
    "frame15",
    "group5",
    "group6",
    "group7",
    "group8",
    "india"
  ],

  frame15: ["frame15", "group5", "group6", "group7", "group8"],
  group5: ["group5", "group6", "group7", "group8"],
  group6: ["group6", "group7", "group8"],
  group7: ["group7", "group8"],
  group8: ["group8"],
  india: ["india"],
  frame16: ["frame16"],
  frame17: ["frame17", "rectangle", "male"],
  rectangle: ["rectangle"],
  male: ["male"],
  frame18: [
    "frame18",
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31",
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame19: [
    "frame19",
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability",
    "frame27",
    "frame28",
    "frame29",
    "frame30",
    "frame31"
  ],

  frame20: [
    "frame20",
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts",
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries",
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame21: [
    "frame21",
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  frame22: [
    "frame22",
    "findAStore",
    "becomeAMember",
    "signUpForEmail",
    "sendUsFeedback",
    "studentDiscounts"
  ],

  findAStore: ["findAStore"],
  becomeAMember: ["becomeAMember"],
  signUpForEmail: ["signUpForEmail"],
  sendUsFeedback: ["sendUsFeedback"],
  studentDiscounts: ["studentDiscounts"],
  frame23: [
    "frame23",
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  frame24: [
    "frame24",
    "getHelp",
    "orderStatus",
    "delivery",
    "returns",
    "paymentOptions",
    "contactUsOnNikecomInquiries",
    "contactUsOnAllOtherInquiries"
  ],

  getHelp: ["getHelp"],
  orderStatus: ["orderStatus"],
  delivery: ["delivery"],
  returns: ["returns"],
  paymentOptions: ["paymentOptions"],
  contactUsOnNikecomInquiries: ["contactUsOnNikecomInquiries"],
  contactUsOnAllOtherInquiries: ["contactUsOnAllOtherInquiries"],
  frame25: [
    "frame25",
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  frame26: [
    "frame26",
    "aboutNike",
    "news",
    "careers",
    "investors",
    "sustainability"
  ],

  aboutNike: ["aboutNike"],
  news: ["news"],
  careers: ["careers"],
  investors: ["investors"],
  sustainability: ["sustainability"],
  frame27: ["frame27", "frame28", "frame29", "frame30", "frame31"],
  frame28: ["frame28"],
  frame29: ["frame29"],
  frame30: ["frame30"],
  frame31: ["frame31"],
  frame32: [
    "frame32",
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved",
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  frame33: [
    "frame33",
    "autoLayoutHorizontal",
    "frame34",
    "_2023NikeIncAllRightsReserved"
  ],

  autoLayoutHorizontal: ["autoLayoutHorizontal", "frame34"],
  frame34: ["frame34"],
  _2023NikeIncAllRightsReserved: ["_2023NikeIncAllRightsReserved"],
  frame35: [
    "frame35",
    "guides",
    "termsOfSale",
    "termsOfUse",
    "nikePrivacyPolicy"
  ],

  guides: ["guides"],
  termsOfSale: ["termsOfSale"],
  termsOfUse: ["termsOfUse"],
  nikePrivacyPolicy: ["nikePrivacyPolicy"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAccountPage__ArgProps,
          internalVariantPropNames: PlasmicAccountPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAccountPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAccountPage";
  } else {
    func.displayName = `PlasmicAccountPage.${nodeName}`;
  }
  return func;
}

export const PlasmicAccountPage = Object.assign(
  // Top-level PlasmicAccountPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphQlFetcher: makeNodeComponent("graphQlFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    accountDetails: makeNodeComponent("accountDetails"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    image: makeNodeComponent("image"),
    accountDetails2: makeNodeComponent("accountDetails2"),
    accountDetails3: makeNodeComponent("accountDetails3"),
    accountDetails4: makeNodeComponent("accountDetails4"),
    defaultAddress: makeNodeComponent("defaultAddress"),
    defaultAddress2: makeNodeComponent("defaultAddress2"),
    frame4: makeNodeComponent("frame4"),
    _125JkNagar: makeNodeComponent("_125JkNagar"),
    frame5: makeNodeComponent("frame5"),
    noida: makeNodeComponent("noida"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    _211378: makeNodeComponent("_211378"),
    frame8: makeNodeComponent("frame8"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    emailAddress: makeNodeComponent("emailAddress"),
    frame11: makeNodeComponent("frame11"),
    joye: makeNodeComponent("joye"),
    frame12: makeNodeComponent("frame12"),
    sharma: makeNodeComponent("sharma"),
    frame13: makeNodeComponent("frame13"),
    _78Xxxxxxxxx: makeNodeComponent("_78Xxxxxxxxx"),
    frame14: makeNodeComponent("frame14"),
    frame15: makeNodeComponent("frame15"),
    group5: makeNodeComponent("group5"),
    group6: makeNodeComponent("group6"),
    group7: makeNodeComponent("group7"),
    group8: makeNodeComponent("group8"),
    india: makeNodeComponent("india"),
    frame16: makeNodeComponent("frame16"),
    frame17: makeNodeComponent("frame17"),
    rectangle: makeNodeComponent("rectangle"),
    male: makeNodeComponent("male"),
    frame18: makeNodeComponent("frame18"),
    frame19: makeNodeComponent("frame19"),
    frame20: makeNodeComponent("frame20"),
    frame21: makeNodeComponent("frame21"),
    frame22: makeNodeComponent("frame22"),
    findAStore: makeNodeComponent("findAStore"),
    becomeAMember: makeNodeComponent("becomeAMember"),
    signUpForEmail: makeNodeComponent("signUpForEmail"),
    sendUsFeedback: makeNodeComponent("sendUsFeedback"),
    studentDiscounts: makeNodeComponent("studentDiscounts"),
    frame23: makeNodeComponent("frame23"),
    frame24: makeNodeComponent("frame24"),
    getHelp: makeNodeComponent("getHelp"),
    orderStatus: makeNodeComponent("orderStatus"),
    delivery: makeNodeComponent("delivery"),
    returns: makeNodeComponent("returns"),
    paymentOptions: makeNodeComponent("paymentOptions"),
    contactUsOnNikecomInquiries: makeNodeComponent(
      "contactUsOnNikecomInquiries"
    ),
    contactUsOnAllOtherInquiries: makeNodeComponent(
      "contactUsOnAllOtherInquiries"
    ),
    frame25: makeNodeComponent("frame25"),
    frame26: makeNodeComponent("frame26"),
    aboutNike: makeNodeComponent("aboutNike"),
    news: makeNodeComponent("news"),
    careers: makeNodeComponent("careers"),
    investors: makeNodeComponent("investors"),
    sustainability: makeNodeComponent("sustainability"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    frame29: makeNodeComponent("frame29"),
    frame30: makeNodeComponent("frame30"),
    frame31: makeNodeComponent("frame31"),
    frame32: makeNodeComponent("frame32"),
    frame33: makeNodeComponent("frame33"),
    autoLayoutHorizontal: makeNodeComponent("autoLayoutHorizontal"),
    frame34: makeNodeComponent("frame34"),
    _2023NikeIncAllRightsReserved: makeNodeComponent(
      "_2023NikeIncAllRightsReserved"
    ),
    frame35: makeNodeComponent("frame35"),
    guides: makeNodeComponent("guides"),
    termsOfSale: makeNodeComponent("termsOfSale"),
    termsOfUse: makeNodeComponent("termsOfUse"),
    nikePrivacyPolicy: makeNodeComponent("nikePrivacyPolicy"),
    // Metadata about props expected for PlasmicAccountPage
    internalVariantProps: PlasmicAccountPage__VariantProps,
    internalArgProps: PlasmicAccountPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAccountPage;
/* prettier-ignore-end */
